{
 "title": "MD1 Dell PowerStore",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "volume_name",
    "label": "Volumes",
    "query": {
     "query": "label_values({job=~\"dell_powerstore_exporter\"},vol_name)"
    }
   },
   {
    "name": "fc_port_name",
    "label": "FC Ports",
    "query": {
     "query": "label_values({job=~\"dell_powerstore_exporter\"},fc_name)"
    }
   },
   {
    "name": "eth_port_name",
    "label": "Ethernet Ports",
    "query": {
     "query": "label_values({job=~\"dell_powerstore_exporter\"},eth_name)"
    }
   },
   { "name": "host", "label": "Host", "query": { "query": "host_latency_write" } }
  ]
 },
 "panels": [
  {
   "title": "Global Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Capacity in Use",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cap_used{instance=\"10.10.10.10:8000\"} * 100 / cap_total{instance=\"10.10.10.10:8000\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
     "options": {
      "content": "## PowerStore-T\n* **Cluster**: MD1T1200.ix.com\n* **Service Tag**: 9FS0QM3\n* **Location**: BMIT MTH R1\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Physical Capacity Total (TB)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cap_total{instance=\"10.10.10.10:8000\"} / 1099511627776"
      }
     ]
    },
    {
     "title": "Physical Capacity Free (TB)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(cap_total{instance=\"10.10.10.10:8000\"} - cap_used{instance=\"10.10.10.10:8000\"}) / 1099511627776"
      }
     ]
    },
    {
     "title": "Logical Capacity Total (TB)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(logical_used{instance=\"10.10.10.10:8000\"} / 1099511627776)"
      }
     ]
    },
    {
     "title": "Data Reduction Ratio",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "data_reduction{instance=\"10.10.10.10:8000\"}"
      }
     ]
    },
    {
     "title": "Overall Health",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "array_health{instance=\"10.10.10.10:8000\"}"
      }
     ]
    },
    {
     "title": "Array IO Size (KB)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "appliance_iosize_total{instance=\"10.10.10.10:8000\"} /1024",
       "legendFormat": "Cluster Bandwidth Read "
      }
     ]
    },
    {
     "title": "Array Latency (ms)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "appliance_latency_total{instance=\"10.10.10.10:8000\"} / 1000",
       "legendFormat": "Cluster Bandwidth Read "
      }
     ]
    },
    {
     "title": "Array IOPS",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "appliance_iops_total{instance=\"10.10.10.10:8000\"}",
       "legendFormat": "Cluster IOPS Read"
      }
     ]
    },
    {
     "title": "Array Bandwidth (MB/s)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "appliance_bandwidth_total{instance=\"10.10.10.10:8000\"} /1048576",
       "legendFormat": "Cluster Bandwidth Read "
      }
     ]
    }
   ]
  },
  {
   "title": "Appliance IOPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Appliance IOPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "appliance_iops_read{instance=\"10.10.10.10:8000\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "appliance_iops_write{instance=\"10.10.10.10:8000\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "appliance_iops_read{instance=\"10.10.10.10:8000\"} + appliance_iops_write{instance=\"10.10.10.10:8000\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Appliance Bandwidth (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "appliance_bandwidth_read{instance=\"10.10.10.10:8000\"} /1048576",
       "legendFormat": "Read "
      },
      {
       "expr": "appliance_bandwidth_write{instance=\"10.10.10.10:8000\"} /1048576",
       "legendFormat": "Write"
      },
      {
       "expr": "(appliance_bandwidth_read{instance=\"10.10.10.10:8000\"} + appliance_bandwidth_write{instance=\"10.10.10.10:8000\"}) /1048576",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Appliance Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "appliance_latency_total /1000", "legendFormat": "Latency" }
     ]
    }
   ]
  },
  {
   "title": "Node A vs Node B",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node A vs Node B IOPS",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "fc_iops_read{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"} + fc_iops_write{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"}",
       "legendFormat": "Total IOPS- {{ fc_name }}"
      }
     ]
    },
    {
     "title": "Node A vs Node B Throughput",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "(fc_bandwitdh_read{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"} / 1048576 ) + (fc_bandwidth_write{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"} / 1048576 )",
       "legendFormat": "Total MB/s- {{ fc_name }}"
      }
     ]
    },
    {
     "title": "Node Affinity",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.*.name", "language": "jsonpath", "name": "Name", "type": "string" },
        { "jsonPath": "$.*.node_affinity", "language": "jsonpath", "name": "Affinity" }
       ],
       "method": "GET",
       "urlPath": "/api/rest/volume?select=name,node_affinity"
      }
     ]
    },
    {
     "title": "Node CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "node_cpu {instance=\"10.10.10.10:8000\"} ",
       "legendFormat": "{{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Level Metrics - $volume_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "volume_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume IOPS Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "vol_iops_read{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"}",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume IOPS Write",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "vol_iops_write{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"}",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume Bandwidth Read (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "vol_bandwith_read{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} /1048576",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume Bandwidth Write(MBps)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "vol_bandwidth_write{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} /1048576",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume Latency Read (ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vol_latency_read{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} / 1000",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume Latency Write(ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "vol_latency_write{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} / 1000",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume IO Size Read (KB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vol_iosize_read{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} /1024",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume IO Size Write (KB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "vol_iosize_write{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} /1024",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Queue Depth Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "round(vol_latency_read{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} * vol_iops_read{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} /1000)",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Queue Depth Write",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 36 },
     "targets": [
      {
       "expr": "round(vol_latency_write{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} * vol_iops_write{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} /1000)",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Volume Capacity ",
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logical_used {instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"}/ logical_provisioned{instance=\"10.10.10.10:8000\",vol_name=~\"$volume_name\"} * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Affinity/VMs",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 42 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.node_affinity", "language": "jsonpath", "name": "Affinity", "type": "string" }
       ],
       "method": "GET",
       "urlPath": "/api/rest/volume/name:$volume_name?select=node_affinity"
      },
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.virtual_machines[*].name", "name": "VM" }
       ],
       "method": "GET",
       "urlPath": "/api/rest/datastore/name:$volume_name?select=name,virtual_machines(name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Port Level Metrics - $fc_port_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "fc_port_name",
   "collapsed": true,
   "panels": [
    {
     "title": "FC port IOPS  Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "fc_iops_read{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"}",
       "legendFormat": "{{fc_name}}"
      }
     ]
    },
    {
     "title": "FC port IOPS  Write",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "fc_iops_write{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"}",
       "legendFormat": "{{fc_name}}"
      }
     ]
    },
    {
     "title": "FC port Bandwidth Read (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "fc_bandwitdh_read{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"} / 1048576",
       "legendFormat": "{{fc_name}}"
      }
     ]
    },
    {
     "title": "FC port Bandwidth Write(MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "fc_bandwidth_write{instance=\"10.10.10.10:8000\",fc_name=~\"$fc_port_name\"} / 1048576",
       "legendFormat": "{{fc_name}}"
      }
     ]
    },
    {
     "title": "Ethernet port Bandwidth Read (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "eth_bandwitdh_read{instance=\"10.10.10.10:8000\",eth_name=~\"$eth_port_name\"} / 1048576",
       "legendFormat": "{{eth_name}}"
      }
     ]
    },
    {
     "title": "Ethernet port Bandwidth Write (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 119 },
     "targets": [
      {
       "expr": "eth_bandwidth_write{instance=\"10.10.10.10:8000\",eth_name=~\"$eth_port_name\"} /1048576",
       "legendFormat": "{{eth_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Level Metrics - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Host IOPS Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "host_iops_read{instance=\"10.10.10.10:8000\",host_name=~\"$host\"}",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host IOPS Write",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "host_iops_write{instance=\"10.10.10.10:8000\",host_name=~\"$host\"}",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host Bandwidth Read (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "host_bandwith_read{instance=\"10.10.10.10:8000\",host_name=~\"$host\"} /1048576",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host Bandwidth Write (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "host_bandwidth_write{instance=\"10.10.10.10:8000\",host_name=~\"$host\"} /1048576",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host Latency Read (ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "host_latency_read{instance=\"10.10.10.10:8000\",host_name=~\"$host\"} / 1000",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host Latency Read (ms)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "host_latency_write{instance=\"10.10.10.10:8000\",host_name=~\"$host\"} / 1000",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host IO Size Read (KB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "host_iosize_read{instance=\"10.10.10.10:8000\",host_name=~\"$host\"} /1024",
       "legendFormat": "{{vol_name}}"
      }
     ]
    },
    {
     "title": "Host IO Size Write (KB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "host_iosize_write{instance=\"10.10.10.10:8000\",host_name=~\"$host\"} /1024",
       "legendFormat": "{{vol_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drive Wear Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drive Health %",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "drive_wear{instance=\"10.10.10.10:8000\"} ",
       "legendFormat": "{{drive_name}}"
      }
     ]
    }
   ]
  }
 ]
}