{
 "title": "Storage Summary GITHUB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "## PowerStore-X\n* **Cluster**: MyPowerStore-X\n* **Service Tag**: 4123AB2\n* **Location**: Room 1B\n"
   }
  },
  {
   "title": "Array IOPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appliance_iops_total{instance=\"10.10.10.10:8000\"}",
     "legendFormat": "Cluster IOPS Read"
    }
   ]
  },
  {
   "title": "Array Bandwidth (MB/s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appliance_bandwidth_total{instance=\"10.10.10.10:8000\"} /1048576",
     "legendFormat": "Cluster Bandwidth Read "
    }
   ]
  },
  {
   "title": "Array Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appliance_latency_total{instance=\"10.10.10.10:8000\"} / 1000",
     "legendFormat": "Cluster Bandwidth Read "
    }
   ]
  },
  {
   "title": "Array IO Size (KB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appliance_iosize_total{instance=\"10.10.10.10:8000\"} /1024",
     "legendFormat": "Cluster Bandwidth Read "
    }
   ]
  },
  {
   "title": "Physical Capacity in Use ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cap_used{instance=\"10.10.10.10:8000\"} * 100 / cap_total{instance=\"10.10.10.10:8000\"}"
    }
   ]
  },
  {
   "title": "Physical Capacity Free (TB)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cap_total{instance=\"10.10.10.10:8000\"} - cap_used{instance=\"10.10.10.10:8000\"}) / 1099511627776"
    }
   ]
  },
  {
   "title": "Data Reduction Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "data_reduction{instance=\"10.10.10.10:8000\"}"
    }
   ]
  }
 ]
}