{
 "title": "Volumes in CloudIQ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "label": "ID", "query": { "query": "label_values(id)" } }
  ]
 },
 "panels": [
  {
   "title": "Volume Total Size (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_total_size{id=~\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Volume Allocated Size (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_allocated_size{id=~\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Volume Data Reduction Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_data_reduction_ratio{id=~\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Volume Snapshot Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_snapshot_count{id=~\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Volume Snapshot Size (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volume_snapshot_size{id=~\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}