{
 "title": "Server GITHUB",
 "time": { "from": "2022-02-17T02:05:53.581Z", "to": "2022-02-17T04:55:18.286Z" },
 "panels": [
  {
   "title": "Fan Speed (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fan_speed{instance=\"10.10.10.11:8000\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature(Celsius)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "temperature{instance=\"10.10.10.11:8000\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "power{instance=\"10.10.10.11:8000\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage (Volts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "voltage{instance=\"10.10.10.11:8000\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}