{
 "title": "Storage Arrays in CloudIQ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "system_type", "label": "System Type", "query": { "query": "label_values(system_type)" } },
   { "name": "name", "label": "Name", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Percentage Storage Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_free_percent{system_type=~\"$system_type\",name=~\"$name\"}",
     "legendFormat": "{{system_type}}, {{name}}"
    }
   ]
  },
  {
   "title": "Storage Free GB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_free_size{name=~\"$name\",system_type=~\"$system_type\"}",
     "legendFormat": "{{system_type}},{{name}}"
    }
   ]
  },
  {
   "title": "Storage IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_iops{system_type=~\"$system_type\",name=~\"$name\"}",
     "legendFormat": "{{system_type}}, {{name}}"
    }
   ]
  },
  {
   "title": "Storage Bandwidth (Mbps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_bandwidth{system_type=~\"$system_type\",name=~\"$name\"}",
     "legendFormat": "{{system_type}}, {{name}}"
    }
   ]
  },
  {
   "title": "Storage Latency (microsecs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "storage_latency{name=~\"$name\",system_type=~\"$system_type\"}",
     "legendFormat": "{{system_type}}, {{name}}"
    }
   ]
  }
 ]
}