{
 "title": "Servers in CloudIQ",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "Name", "query": { "query": "label_values(name)" } },
   { "name": "model", "label": "Model", "query": { "query": "label_values(model)" } }
  ]
 },
 "panels": [
  {
   "title": "Server Inlet Temperature (C)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_inlet_temperature{model=~\"$model\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Power Consumption (Watt)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_power_consumption{model=~\"$model\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_cpu_usage_percentage{model=~\"$model\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Server Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_mem_usage_percentage{model=~\"$model\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}